package dev.darttools.flutter_android_volume_keydown_example;

import dev.darttools.flutter_android_volume_keydown.FlutterAndroidVolumeKeydownActivity;

public class MainActivity extends FlutterAndroidVolumeKeydownActivity {
}
